# torchtitan Config.toml
# NOTE: this toml config is a preset for 64 A100 GPUs.

[job]
dump_folder = "./outputs_TinyLlama3"
description = "Llama 3 Tiny training"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 2500

[metrics]
log_freq = 10
enable_tensorboard = true
save_tb_folder = "tb"

[model]
name = "llama3"
flavor = "Tiny"
norm_type = "rmsnorm"  # [layernorm / np_layernorm / rmsnorm / fused_rmsnorm]
tokenizer_path = "./torchtitan/datasets/tokenizer/original/tokenizer.model"

[optimizer]
name = "AdamW"
lr = 4e-4

[training]
batch_size = 8
seq_len = 2048
warmup_steps = 200  # lr scheduler warm up
max_norm = 1.0  # grad norm clipping
steps = 10000000
data_parallel_degree = 2
tensor_parallel_degree = 1
pipeline_parallel_degree = 1
fp8_linear = ""
compile = false
dataset = "slimpajama+starcoderdata"

[checkpoint]
enable_checkpoint = true
keep_latest_k = 50
folder = "checkpoint"
interval_type = "steps"
interval = 25000
model_weights_only = false
export_dtype = "bfloat16"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'selective'  # ['none', 'selective', 'full']
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy
